# Install dependencies only when needed
FROM cypress/base:14.17.0
WORKDIR /app
COPY . .
RUN npm ci

ENV NODE_ENV testing
ENV CI true

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build:test

CMD ["npm", "run", "e2e:headless"]
