import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import { PageHeader } from 'antd';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PageHeader>
				<Link passHref={true} href="/repositories">
					<a>Show repositories</a>
				</Link>
			</PageHeader>
		</div>
	);
};

export default Home;
